[package]
name = "rust-project"
version = "0.1.0"
authors = ["'Toyosi Adekanmbi <oluwatoyosiadeleye4@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
